<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBIx97UR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBIx97UR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBIx97UR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBIx97UR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBIx97UR\App_KernelDevDebugContainer([
    'container.build_hash' => 'BIx97UR',
    'container.build_id' => 'b82a2e45',
    'container.build_time' => 1730370245,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBIx97UR');
